### ISSUE TITLE
Add {{navigation}} support to Casper

### ISSUE THREAD

**Issue by JohnONolan** [TryGhost/Casper#173]
Initial navigation support for Casper - going to keep it simple to start, with the slide-along menu here http://tympanus.net/Development/SidebarTransitions/

Initially this can be triggered from the blog-logo.

@PaulAdamDavis mind doing the first pass on this? I can't think of any special considerations or additional notes at the moment.

**Comment by qLb** [comment]
Initially this can be triggered from the blog-logo. - i do not recommend that for pure semantics. standard expected behavior  is "go back to home page"
i think [this](https://developer.android.com/design/patterns/gestures.html) is sensible for mobiles but i won't lie it's ideal or anything. it has some proper background on user interactions though.
