### ISSUE TITLE
Text in Casper antialiased sometimes, but sometimes not

### ISSUE THREAD

**Issue by kostyakoz** [TryGhost/Casper#259]
### Issue Summary

Sometimes text in my blog based on default non-modified Casper theme is antialiased, and sometimes not. There are difference in browsers, I want to finally remove antialiased text. Is it possible?
### Steps to Reproduce

I think picture on page will reproduce this problem, pages without images display text normal, without antialiasing.

![screen shot 2016-07-11 at 16 30 36](https://cloud.githubusercontent.com/assets/1935229/16732439/3ea4f244-478e-11e6-89f6-ac52c43d5052.png)
![screen shot 2016-07-11 at 16 30 46](https://cloud.githubusercontent.com/assets/1935229/16732441/415e4f26-478e-11e6-811e-331359857ed0.png)
![screen shot 2016-07-11 at 16 31 27](https://cloud.githubusercontent.com/assets/1935229/16732442/42a25562-478e-11e6-812a-4d64b65d0ef1.png)
### Technical details:
- Ghost Version: 0.8
- Node Version: 4.2.6
- Browser/OS: Chrome, Safari on OS X 10.11
- Database: SQLite

**Comment by mechadrops** [comment]
Yeah, the antialiasing only applies when the post **doesn't** have a post cover image, and doesn't apply when **there is** a cover image. However, this difference only appears in Chrome and Safari. There's no difference in rendering in Firefox. Here's a gif showing the difference in Chrome: http://i.imgur.com/GTFIi88.gif
This is still present in Ghost v0.10.0 on Windows 10.
Antialiasing makes the text look too light, I think.

**Comment by mechadrops** [comment]
Yeah, the antialiasing only applies when the post has an image in the body, and doesn't apply when there are no images. However, this difference only appears in Chrome and Safari. There's no difference in rendering in Firefox. Here's a gif showing the difference in Chrome: http://i.imgur.com/42XLFB9.gif
This is still present in Ghost v0.10.0, viewed on Windows 10.
Antialiasing makes the text look too light, I think.

**UPD**: it also has something to do with "transform: translate3D" function used in the navigation styling.
If you try opening your screen.css and simply remove this part of the code:
```
body.nav-closed .nav {
    -webkit-transform: translate3D(97px, 0, 0);
        -ms-transform: translate3D(97px, 0, 0);
            transform: translate3D(97px, 0, 0);
}
```
You'll notice that the antialiasing will be gone. Once you click on "Menu", it will apply again.
You can also change the _body.nav-closed .nav_'s transform value from 97px to 240px or more, which will also remove the antialias. Notice how the 240px value coincides with _body.nav-opened .site-wrapper_'s value. 

'Navigation' part of the css is responsible not just for the navigation menu but also for moving the text around the screen when the navigation is opened, and something about the current code results in antialiasing.
You can google "translate3d blur" and there'll be dozens of results about the blur problems this function.

I'm not sure what to do with all this because I'm not a web developer, maybe someone more knowledgeable will come up with a fix.

**Comment by JohnONolan** [comment]
This has been open for almost a year - so I'm going to close it for now. If anyone reports or comes up with a fix in future then we can look at it again
