### ISSUE TITLE
Improve loading

### ISSUE THREAD

**Issue by BirkhoffLee** [TryGhost/Casper#264]
* Resources with a "?" in the URL are not cached by some proxy caching servers. Remove the query string and encode the parameters into the URL. Like these:
```
https://blog.birkhoff.me/assets/css/screen.css?v=832a8bc95b
https://blog.birkhoff.me/assets/fonts/casper-icons.woff?v=1
https://blog.birkhoff.me/assets/js/index.js?v=832a8bc95b
https://blog.birkhoff.me/assets/js/jquery.fitvids.js?v=832a8bc95b
```
* Gravatar image dimensions. I found that some places only display 24x24 of the image, but Casper download 250x250 of the image. Thus if you specify dimensions of the image in the gravatar url, the image size can be reduced up to 99%.

**Comment by kevinansfield** [comment]
> Resources with a "?" in the URL are not cached by some proxy caching servers.

Please see [this issue](https://github.com/TryGhost/Ghost/issues/7093) - it's Ghost that adds cache-busting to assets rather than Casper and `?`s in URLs are not a problem as far as we're aware, if you have concrete evidence that it's a widespread issue and not a peculiarity of an individual's setup please add to the referenced issue.

> Gravatar image dimensions. I found that some places only display 24x24 of the image, but Casper download 250x250 of the image.

The image is at a suitable size for retina screens, downloaded once, cached, and used everywhere for both small and large representations - I'm not sure the file size optimisation would outweigh the multiple requests needed to download gravatars at multiple sizes or the benefits gained from having a single size across a large number of Casper variants that can all re-use the same cached image.

**Comment by KayakinKoder** [comment]
This is a widespread problem now in 2020. How to reproduce:

- Make a change to your CSS
- Deploy your theme
- Load your site using Chrome latest on a Win 10 machine

The new CSS is not loaded.
