### ISSUE TITLE
Previous post didn't appear as usual in the last post.

### ISSUE THREAD

**Issue by norsasono** [TryGhost/Casper#266]
This is the preview of my footer [https://blog.sasono.web.id/2016/08/02/update-ghost-0-9-0-using-openshift-quickstart/](https://blog.sasono.web.id/2016/08/02/update-ghost-0-9-0-using-openshift-quickstart/)
![ghost](https://cloud.githubusercontent.com/assets/11081536/17855188/75a9afc6-68a1-11e6-85f9-893458c552fc.png)

Different from this one [https://demo.ghost.io/style-test/](https://demo.ghost.io/style-test/)
![ghost 2](https://cloud.githubusercontent.com/assets/11081536/17855215/a661bd7a-68a1-11e6-9dec-31a093e60b5e.png)

**Comment by ErisDS** [comment]
Just to clarify, the bug here is that the "read this next" post is the same as the post you are already reading?

Can you provide some information about your blog environment? When you hit the "new issue" button there should have been a template. Specifically your Ghost version would be useful. Also can you tell us what timezone both your server and blog are configured to?

**Comment by ErisDS** [comment]
@norsasono ping? I've re-raised this as a bug against Ghost here: https://github.com/TryGhost/Ghost/issues/7248

Would be super helpful for a fix if you could answer my questions.
