### ISSUE TITLE
Add Content Security Policy support

### ISSUE THREAD

**Issue by oxdef** [TryGhost/Casper#277]
There is a mechanism called Content Security Policy which web applications can use to mitigate a broad class of content injection vulnerabilities, such as cross-site scripting (XSS). Content Security Policy is a declarative policy that lets the authors (or server administrators) of a web application inform the client about the sources from which the application expects to load resources.

It will be great if default theme for Ghost will support it out of the box and enforce by default. In the most cases implement CSP support into web applicaton consist of following steps:

1. Review HTML code and try to remove all inline code (JS and CSS) and eval() usage
2. If you can't remove inline code you should use nonces/hashes
3. Prepare CSP policy and switch it on in Report-Only mode for some time
4. Fix all the bugs from the CSP log
5. Switch CSP into block mode

We can embed CSP in Casper via [`meta` tag](https://www.w3.org/TR/CSP2/#delivery-html-meta-element)  into `default.hbs`.  I had tested following CSP value for  version 1.3.0:

```
default-src 'none'; script-src https://code.jquery.com 'self'; style-src https://fonts.googleapis.com 'self' 'unsafe-inline'; img-src * data:; font-src https://fonts.googleapis.com https://fonts.gstatic.com 'self';
```

NB! 
> Authors are strongly encouraged to place meta elements as early in the document as possible, because policies in meta elements are not applied to content which precedes them. In particular, note that resources fetched or prefetched using the Link HTTP response header field, and resources fetched or prefetched using link and script elements which precede a meta-delivered policy will not be blocked.

Additional information:
* https://www.w3.org/TR/CSP2/
* http://githubengineering.com/githubs-csp-journey/
* http://www.html5rocks.com/en/tutorials/security/content-security-policy/
* https://developer.mozilla.org/en/docs/Web/Security/CSP/CSP_policy_directives
* https://oxdef.info/csp-tester/

**Comment by Yinchie** [comment]
This should be done on the server level (HTTP header) and not in a meta tag if you care about security (content injection attacks).

Also, this will limit the user's possibility to add additional things to the website if they do not understand CSP, e.g. Facebook and/or Disqus comments, Not user friendly.

**Comment by oxdef** [comment]
1. Software should be secure **by default**
2. CSP via header is the best choice but it needs the end user of the Ghost to build policy value and make changes in web server configuration file. It is ok for advanced users but not for regular ones.
3. For most cases CSP via meta tag should be normal solution if corresponding meta tag is placed in the top of head section.
4. CSP in context of blog part (**not admin interface**) is depended on the theme and developer of the theme knows best what sources should CSP value consist of for the theme

But, yes, it can lead problems with Code Injection via admin interface... ;-( Do you have any ideas how can we add easily CSP and not break this functionality? May be we can start with recommendations in REAME file what default CSP value can be used for the theme?

**Comment by Yinchie** [comment]
Nothing is 100% secure.

I personally have it configured very well on my own website but it is often very annoying to configure right if you want a -very tight- secure setup e.g. for embedding a Flickr photo using their embedding code you need to add multiple domains and subdomains in different CSP sections which you only find out after using developer tools in the browser.. Most people do not find it necessary to go through the trouble and look at other websites around the web that also do not have it configured.

Once again, I personally think it will be difficult for the common user to configure it for a tight secure setup. 

I took a look at your own website and even you did not configure it correctly according to developer tools, throwing massive errors that certain fonts are refused to load because it violates content security policy.

Also, you miss certain parts for CSP. You will also need the following for compatibility reasons.
X-Content-Security-Policy and X-WebKit-CSP

Highly recommended: reflected-xss block

**Comment by oxdef** [comment]
I'm a little bit surprised about your comment :)

> I took a look at your own website and even you did not configure it correctly according to developer tools, throwing massive errors that certain fonts are refused to load because it violates content security policy.

Could you please give examples of such errors? Here or via email oxdef@oxdef.info. Because I don't see any errors in Chromium and Firefox devtools.

> Also, you miss certain parts for CSP. You will also need the following for compatibility reasons. X-Content-Security-Policy and X-WebKit-CSP

In now days, no, you don't need to do it. It is not standard headers and it adds complexity. 

> Highly recommended: reflected-xss block

1. It is not part of CSPv2 standard which is the last stable one and not part of future CSPv3 
2. It also adds complexity. 

So let's return to the issue.  What do you think about that we can start with recommendations in REAME file what default CSP value can be used for the theme?

**Comment by Yinchie** [comment]
Apparently, you have base64 encoded woff fonts, which are refused to load on your website because your font-src does not contain "data:".

Backward compatibility is always important, it is why companies like Cloudflare still use a broad range SSL ciphers and TLS protocols. Or else a lot of people won't be visit websites.
Like there are still a lot of people using Windows XP using the IE browser. And IE 11 only supports "X-Content-Security-Policy".
IE edge does not even support Content Security Policy Level 2 and Firefox only has partial support.

Recently Cloudflare also started using TLS 1.3, yet most browsers except Firefox support it.

**Comment by oxdef** [comment]
> Apparently, you have base64 encoded woff fonts, which are refused to load on your website because your font-src does not contain "data:".

Could you please send me via email screenshot of devtools console plus browser name and version information?

It is important for you to have backward compatibility in case of modern technologies based blogging platform. Well, ok. I want to return back this conversion to the issue. Let's help advanced users and add to `REAME` file recommendations what they need to add into CSP if they want to have it? I don't mind if we add examples **for all** header names which you have mentioned above.

**Comment by ErisDS** [comment]
This something that needs to be done in Ghost rather than the theme level. There is an open discussion here: https://github.com/TryGhost/Ghost/issues/7206. That discussion has dried up as there is no clarity about how this could be implemented, and therefore input from fresh eyes would be welcome.
