### ISSUE TITLE
Ghost 1.0: @blog.url contains trailing slash by default

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/Casper#297]
Part of the url refactoring in Ghost 1.0 was to make the url helper consistent. Asking Ghost for any url will contain a trailing slash.

This causes double slashes, for example in the navigation menu:
https://github.com/TryGhost/Casper/blob/master/partials/navigation.hbs#L12

Either we ensure in 1.0, that the `@blog.url` contains no trailing slash or we adapt the casper `ghost-1.0` branch.

**Comment by ErisDS** [comment]
Ideally, people wouldn't do things like `{{@blog.url}}/rss/` as we do in Casper, rather we'd have support for something like `{{url "rss"}}` or `{{url "/subscribe/"}} where Ghost sorts the paths out, however I am not sure that is a realistic solution at this point? 

It does make sense to always make `{{@blog.url}}` end in a trailing slash, for lots of cases, but because it is the opposite to what Ghost 0.11 does, I guess this will result in a lot of double slashes in themes. Although this doesn't look good, it doesn't have any impact - all browsers ignore it and treat it like a single slash.

**Comment by JohnONolan** [comment]
https://github.com/TryGhost/Ghost/issues/8569
