### ISSUE TITLE
Author & Pub Date in Article tag in Casper Theme Causes Strange Search Results

### ISSUE THREAD

**Issue by mattferderer** [TryGhost/Casper#305]
### Issue Summary

The Casper theme (which many other themes use as a starter) includes the title of the post and the publish date within the article tag. It appears that this causes issues in Bing & Google's search results. See photo:
![capture](https://cloud.githubusercontent.com/assets/2480667/25545250/8c776590-2c23-11e7-875e-702f140bc3b6.JPG)

In my theme, which was based on Casper, it seems that by removing these out of the article tag it fixes the issue. Since they're at the top of the article tag, I just made a separate div tag above the article tag for that info to live. 

### Technical details:

* Ghost Version: 0.11.8

**Comment by JohnONolan** [comment]
This is a bit of a misnomer. What's happening here that no explicit meta description has been set, and the search term is "the post title"

When no explicit meta description is defined, Google scans the content of the page for the search term, and then outputs the content immediately following/surrounding it. In this instance, because the title of the post is what's being searched for, the content which immediately follows on the page is some meta data.

If you searched for some other sentence contained in the post, you wouldn't see this. Likewise, moving meta data out into a different div only solves this singular use-case, it doesn't actually affect anything else :)

So, I don't think this is a bug!
