### ISSUE TITLE
Old Ghost Strips Div

### ISSUE THREAD

**Issue by goodroot** [TryGhost/Casper#331]
We appropriated Casper 2.0 and plugged it into Old Ghost this morning; we have Ghost Pro and haven't been upgraded yet.

The div that's being stripped is this one:

![pasted image at 2017_07_27 02_01 pm](https://user-images.githubusercontent.com/9484709/28688208-f6aeeb20-72c5-11e7-828c-88c204d6d9f3.png)

It's causing things to align funny.

Locally, latest Ghost (1.0.2):

![screen shot 2560-07-27 at 12 20 38 pm](https://user-images.githubusercontent.com/9484709/28688246-0c9f0e92-72c6-11e7-847a-3ba746efad23.png)

Production, Old Ghost (/shrug):

![screen shot 2560-07-27 at 12 20 44 pm](https://user-images.githubusercontent.com/9484709/28688262-1e1058c0-72c6-11e7-9aa9-8ca1cb53c091.png)

The solution is to "use the latest Ghost", but I felt it will be useful to have an issue open incase others discover it.

**Comment by AileenCGN** [comment]
Hey @goodroot! This is known and Casper 2.0 was never intended to work with Ghost < 1.0. And yes, the missing Koenig editor in Ghost 0.11.x versions is the reason for the images and blockquotes being off.

I'm closing this issue, as it's not an issue with Casper because the minimal Ghost version for it is 1.0.
