### ISSUE TITLE
Blog Detail Page CSS Issues

### ISSUE THREAD

**Issue by bharatramnani94** [TryGhost/Casper#341]
Open any detail (post) page (Eg: https://demo.ghost.io/advanced-markdown/), the CSS is messed up. The blog post isn't readable at all.

<img width="1440" alt="screen shot 2017-08-02 at 12 53 04 pm" src="https://user-images.githubusercontent.com/7734410/28862145-94ee70a2-7781-11e7-9cc4-1c9c3f0cc3ec.png">
<img width="1440" alt="screen shot 2017-08-02 at 12 53 07 pm" src="https://user-images.githubusercontent.com/7734410/28862146-94f67e0a-7781-11e7-9189-0016fca34e79.png">

**Comment by AileenCGN** [comment]
Hey @bharatramnani94! To reproduce this bug, we'd need some more information! Which browser and version are you running? Does it happen to other browser to you as well? Which OS?

We've experienced some issues when users have "Experimental Web Platform Features" in Chrome enabled.

**Comment by vikaspotluri123** [comment]
@AileenCGN I had the same issue w/ the Ghost Dev blog (which is also running Casper 2.0)

[Issue summary](https://ghost.slack.com/archives/C04CUS2R3/p1501514729718701)
[Screenshot](https://files.slack.com/files-pri/T025584C4-F6FSXDA3V/pasted_image_at_2017_07_31_10_25_am.png)

This issue is _does not_ show up w/ the latest build (62.0.3174.2)

**Comment by JohnONolan** [comment]
If you use bleeding edge nightlies of development browsers, you are going to find bugs in those browsers. That isn't anything to do with this repository.
