### ISSUE TITLE
Theme nav is not responsive

### ISSUE THREAD

**Issue by lukekhamilton** [TryGhost/Casper#344]
Theme nav is not responsive on mobile with more that 5 ideas in the nav.

**Comment by AileenCGN** [comment]
Hey @lukekhamilton! The theme nav is scrollable:

![theme_nav](https://user-images.githubusercontent.com/8037602/28993077-2eeb6370-79d7-11e7-9169-afd8cef3f4de.gif)

**Comment by lukekhamilton** [comment]
Ok thanks for that. However I would say that's pretty poor UX as its wasnt
really all that obvious to someone thats pretty tech savvy.

Would really love to see this improved.

Kind regards,
Luke Hamilton
Online business consultant​

--
e: luke@mettadata.com
s: lukekhamilton
c: *https://calendly.com/lukekhamilton/
<https://calendly.com/lukekhamilton/>*

 ~ With loving kindness ~

**Comment by cobbspur** [comment]
This has been raised a few times now as not being obvious/desirable which is a shame considering the overall very positive feedback to Casper 2.0. @JohnONolan just as an FYI

**Comment by conorgil** [comment]
I would also love to see this issue reopened and addressed by the Ghost team. I just launched a site using Ghost Pro and the first thing my users said to me was that the navigation menu is broken on mobile. The hamburger menu is a pretty universal paradigm on mobile these days and I've never seen a nav menu that I had to scroll. I **could** fix this myself, but the reason that I paid for Ghost Pro is to not spend time on boilerplate stuff like this. I realize that I'll need to tweak the default theme for issues specific to my site, but navigation is pretty universal to everyone.

Any chance the Ghost core team would reconsider this since it is the default theme?

**Comment by JohnONolan** [comment]
This issue has been addressed by the Ghost team, and is not a bug.

Scrolling navigation is a simple, common paradigm implemented my many other mainstream sites - including, but not limited to apple.com and medium. The hamburger menu is not a universal paradigm, and it has numerous problems of its own. These are well documented and easily available with a couple of google searches. Believe it or not, when Casper did have a hamburger menu in a previous version, we also got issues with outraged people complaining about how terrible hamburger menus are. 

Ghost(Pro) is managed hosting - as in servers - it is in no way related to any theme. 

If you don't like the Casper theme, there are many others to choose from on marketplace.ghost.org - some of them even use hamburger mobile menus if that's what you want.
