### ISSUE TITLE
Post card sizes look uncomfortable

### ISSUE THREAD

**Issue by ImKcat** [TryGhost/Casper#347]
I don't know whether other people feels, but I think some of these post cards are too hight or too big

See screenshots below:
![screenshot 1](https://user-images.githubusercontent.com/7700379/29153774-06a630ae-7dc2-11e7-8c42-24b576594d54.jpg)
![screenshot 2](https://user-images.githubusercontent.com/7700379/29153778-0ccdd072-7dc2-11e7-8360-bf995bd7a2c9.jpg)

I think reason is post image, I saw [official demo](https://demo.ghost.io/) post image size was 1400 x 933, so I tried to change every post image size in my blog, but the result was first post card same as official demo, others post cards change nothing or change a little bit

Check my [blog](https://imkcat.com)

> **Detail**
> Ghost 1.5.1
> Casper 2.0.2

**Comment by ImKcat** [comment]
Upgrade to 2.0.3, same as 2.0.2

**Comment by kevinansfield** [comment]
@ImKcat the card size is determined by the amount of text, Casper uses the the [`{{excerpt}}`](https://themes.ghost.org/docs/excerpt) helper with a ["words" setting of 33](https://github.com/TryGhost/Casper/blob/master/partials/post-card.hbs#L16) which for English works OK.

I think the problem you're seeing arises because the helper can only count spaces as "words" so when using certain languages which don't have english like word boundaries you end up with more content than desired. I would suggest adapting your theme to use the [`characters`](https://themes.ghost.org/docs/excerpt)` parameter or using the new [custom excerpt](https://blog.ghost.org/custom-excerpts/) feature to tailor the content that is displayed in each post.

I'm going to close this issue as it's not a problem in Casper itself and Ghost has added features to work around the limitations of the `{{excerpt}}` helper.

**Comment by ImKcat** [comment]
@kevinansfield Thanks ; )
