### ISSUE TITLE
Formatting in Casper stories in IE11 and Edge.

### ISSUE THREAD

**Issue by temabu** [TryGhost/Casper#376]
![formatting-on-ghost](https://user-images.githubusercontent.com/6004995/29746860-029b0fa4-8b2b-11e7-9102-a30c1eee2ba4.JPG)

### Steps to Reproduce
 
Formatting in stories is all wrong in IE 11.  See image above.  Chrome on right - IE11 on left.
Text and images are the wrong size and all centred in IE11.

### Technical details

* Casper Version: 2.06
* Ghost Version: 1.7.1
* Browser Version: IE11 11.0.10240.17533 (Update Version 110.45)
* OS Version: Win 10

**Comment by AileenCGN** [comment]
Same as #371. Seems to happen even in newer versions, @JohnONolan

**Comment by akshaybabloo** [comment]
Isn't IE legacy now?

**Comment by frederikaalund** [comment]
> Isn't IE legacy now?

[Internet Explorer has end-of-life status](https://en.wikipedia.org/wiki/Internet_Explorer#End_of_life). However, quoting the same article:

> ...[Internet Explorer] will continue to be maintained as part of the support policy for the versions of Windows with which it is included.

So Internet Explorer still has active support from Microsoft as long as Windows 7 has support. I think that is a good enough reason to continue supporting Internet Explorer until Windows 7 reaches end-of-life or the Internet Explorer's market share surges significantly (currently 12.7%).

Anecdotally, I received a complaint yesterday from an Internet Explorer user who had visited our website. These users still exist whether we like it or not. Typically, they are enterprise users who must use Internet Explorer because of company policies.

**Comment by frederikaalund** [comment]
Temporary fix:

    .kg-card-markdown > * {
        max-width: 100%; /* Fix for Internet Explorer 11 */
    }

I use the above in production now and it does the trick. There are still some small issues with post images being slightly too large. Nothing major.

**Comment by vinzent** [comment]
The fix of @frederikaalund did also work for me.

@JohnONolan would you accept a PR with this simple fix?

**Comment by JohnONolan** [comment]
That selector is terrible for performance. Seems like a hack more than a fix? Anyone who is affected by this (and cares about it) is more than welcome to investigate it and if a proper fix is proposed then I'd be very happy to merge it.

**Comment by frederikaalund** [comment]
My 'fix' was indeed meant as a temporary workaround. I'm still very much looking forward to a proper fix.

**Comment by vinzent** [comment]
unfortunately i'm not able to provide a better fix because of lacking knowledge in this domain.

AFAIK out there are many corporate IE11 browsers and they don't have a good experience with the default ghost template. even with ghost(pro).

**Comment by juan-g** [comment]
Possible solutions:

[css - Text in a flex container doesn't wrap in IE11 - Stack Overflow](https://stackoverflow.com/questions/35111090/text-in-a-flex-container-doesnt-wrap-in-ie11)

**Comment by robotnoises** [comment]
Could we potentially fix this by isolating the "hacky-ness" of it to only IE?

```
@media screen and (-ms-high-contrast: active), (-ms-high-contrast: none) {
    .kg-card-markdown > * {
        /* Fixes a flexbox bug in IE where the text overflows its container */
        max-width: 100%;
    }
 }
```

**Comment by JohnONolan** [comment]
Yeah that would be an acceptable interim fix 👍 :)

**Comment by geniot** [comment]
I'm using Ghost version 2.1.4. The problem still exists in IE 11. The css selector has changed to .post-content > * though.

**Comment by JohnONolan** [comment]
This issue is over a year old, so I'm going to do a quick finally summary and then close it:

- The IE11 bug is valid
- There is no way to fix it without rewriting the entire layout logic of Casper
- We will probably do that at some point, in Casper 3.0, but it's not happening before then
- If you need this fixed, you can always fix it in your copy of Casper - there's nothing wrong with that. We simply won't be merging any of the workaround fixes into upstream because none of them work universally
