### ISSUE TITLE
[Development] Add support for gscan

### ISSUE THREAD

**Issue by vikaspotluri123** [TryGhost/Casper#379]
This is a feature request, although I'm willing to be the one to write the code for it 😄 

Since casper is the starting point for a lot of theme development, I think testing against [gscan](https://github.com/tryghost/gscan) should be supported. That way themes that use Casper as the base can also take advantage of being tested (potentially as part of the development workflow), and the load on the [official tester](https://gscan.ghost.org) will be reduced (although I'm not sure that's really something to worry about 😆) 

Before I create a pull request implementing it in my own way, I want to reach out to the community / the Ghost team to see what they think about it - is this feature actually needed, how would you implement it, etc.

My current thoughts on how to implement it are via a script (i.e. `npm gscan`) or through the gulp file (although the issue with this idea is  there is no gulp plugin). These are more of my initial thoughts, rather than something set in stone.

Technical details: [not applicable]

**Comment by ErisDS** [comment]
Hi @vikaspotluri123 :) 

I fully understand what you're getting at here, so I've updated our documentation to explain that the official tester can be used as a command line tool, in places where theme devs may discover it. Specifically [here](https://themes.ghost.org/v1.7.0/docs/gscan#section-command-line) and [here](https://docs.ghost.org/v1/docs/install-local#section-developing-themes).

Hopefully this provides a clear way to do what you need to and so I don't think there is a need to add any code to Casper. I think that adding an `npm` alias & dev dependency to Casper might cause more confusion rather than less, because then Casper would have a slightly different way to do it than the officially recommended and documented way.
