### ISSUE TITLE
User-Select & Header Background when editing default.hbs

### ISSUE THREAD

**Issue by justinboden** [TryGhost/Casper#421]
css/screen.css doesn't appear to be equivalent to built/screen.css

Couldn't get Gulp to run on machine so edited default.hbs to point to css/screen.css instead of built/screen.css. This appears to result in a more newbie-editable version of Casper except for the following two issues.

Header background defaults to background color (white) and user-select is apparently reset to none (can't select text).

I know that editing default.hbs in the above manner lacks a lot of elegance, but I also know Casper is meant to be the newbie-accessible theme, and it would make sense to me that both screen.css files should be equivalent in regards to basic things like background color and text selection. If this isn't an unreasonable expectation, is there a fix to be found here?

### Technical details

* Casper Version: latest
* Ghost Version: latest
* Browser Version: Chrome (latest)
* OS Version: OSx (latest)

**Comment by kevinansfield** [comment]
Colors and so on are handled by PostCSS in order that CSS variables (which don't have full browser support yet) are usable.

It's necessary to use `gulp` to build the CSS file, there won't be out of the box equivalence if you rename or copy/paste the src file because browser support just isn't there for a number of CSS features and properties without the browser extension prefixes.

**Comment by markhillard** [comment]
@kevinansfield, I'm running into a similar issue here, but I have gulp working and I've run `gulp css` to build out the CSS files. What I'm noticing is that the PostCSS custom properties and color vars are not compiling down to a single color value for certain elements.

So in the new built screen.css, I'm seeing these properties showing up before the reset:

`:root{--blue:#3eb0ef;--green:#a4d037;--purple:#ad26b4;--yellow:#fecd35;--red:#f05230;--darkgrey:#15171a;--midgrey:#738a94;--lightgrey:#c5d2d9;--whitegrey:#e5eff5;--pink:#fa3a57;--brown:#a3821a}a,abbr,acronym,address...`

Then later in the file, for example, I'm seeing this:

`::selection{text-shadow:none;background:#cbeafb;background:color(var(--blue) lightness(30%))}`

If I compare with the original built screen.css file of the Casper theme these variables don't show up at all and anywhere color variables are processed I'm seeing the correct, compiled color value.

I've been searching high and low to try and find a solution but no luck yet. This issue seemed pretty close to what I'm experiencing, so I figured I'd comment here rather than create a new issue.

### Technical details

* Casper Version: latest
* Ghost Version: latest
* Browser Version: Chrome Canary (latest) and Firefox Dev Edition (latest)
* OS Version: Windows 7 Enterprise (SP1)
* Node: 6.13.1 (not sure if this makes a difference?)

**Comment by kevinansfield** [comment]
> So in the new built screen.css, I'm seeing these properties showing up before the reset:
>
> `:root{--blue:#3eb0ef;--green:#a4d037;--purple:#ad26b4;--yellow:#fecd35;--red:#f05230;--darkgrey:#15171a;--midgrey:#738a94;--lightgrey:#c5d2d9;--whitegrey:#e5eff5;--pink:#fa3a57;--brown:#a3821a}a,abbr,acronym,address...`
>
> Then later in the file, for example, I'm seeing this:
>
> ::selection{text-shadow:none;background:#cbeafb;background:color(var(--blue) lightness(30%))}

It sounds like you've somehow got a newer version of the postcss plugins installed. The output you are showing there is valid CSS because it's now supported in browsers and includes necessary fallbacks, _however_ you shouldn't be seeing that output if you have the same versions of plugins installed as the ones specified in `package.json` and `yarn.lock` 😕

**Comment by markhillard** [comment]
@kevinansfield, thank you, that makes sense. I'll check my plugin versions.

**Comment by markhillard** [comment]
@kevinansfield, I downgraded those packages via npm and re-tested. Everything is working as expected now, so feel free to close this issue.
