### ISSUE TITLE
npm package out-of-date

### ISSUE THREAD

**Issue by mars** [TryGhost/Casper#427]
First of all, thank you for creating and maintaining this theme. It is a beautiful, highly-functional default for Ghost 🌈👻

Projects that use Ghost as an npm module (e.g. [ghost-on-heroku](https://github.com/cobyism/ghost-on-heroku)) must specify the Casper theme dependency from git (see ghost-on-heroku's [package.json](https://github.com/cobyism/ghost-on-heroku/blob/master/package.json#L13)).

git-based dependencies prevent `npm update` to newer versions. Instead, the current version of Casper must be manually looked-up and revised.

The npm registry contains a [casper-theme](https://www.npmjs.com/package/casper-theme), but it is woefully out-of-date.

Is there a reason casper-theme package is not kept up-to-date? Would it be possible to add `npm publish` to your Casper release process?

**Comment by vikaspotluri123** [comment]
The `casper-theme` npm pacakge you linked to doesn't look like it's maintained by ghost. The [collaborators list](https://www.npmjs.com/package/casper-theme/access) shows only 1 user, who hasn't had [[m]any contributions to the Ghost codebase](https://github.com/search?q=org%3ATryGhost+PaulBGD)

So I guess to answer your question "Why is the casper-theme pacakge not kept up-to-date", the answer is because Ghost doesn't own it 😄

**Comment by mars** [comment]
Indeed @vikaspotluri123 that's true. It's the sad state of affairs with many npm packages.

My point with this issue is to bring attention to the out-of-date package and the usefulness of an official package.

**Comment by JohnONolan** [comment]
There's only so many different use-cases that we can maintain with a small core team - the reason we don't officially support a Casper npm package is because we don't use Heroku or have any use for one - so it's not on our radar at all. 

The ghost-on-heroku repo is equally not maintained by us, so if a Casper npm package is required to work with ghost-on-heroku, then the best people to maintain that would likely be the same people who make ghost-on-heroku :) maybe try this issue on their repo and see if it has any traction with others who have the same use-case as you

**Comment by mars** [comment]
Hi @JohnONolan! Thanks for your swift reply 🙏

Totally understand the capacity & scope situation. The ghost-on-heroku project (I'm a collaborator) does not want to be in the business of maintaining an unofficial package of someone else's module. So we'll continue depending on Casper as a npm+git dependency.

Thanks for making Ghost itself an npm package 🎁🤩 Cheers!
