### ISSUE TITLE
New Infinite Scroll Spec

### ISSUE THREAD

**Issue by JohnONolan** [TryGhost/Casper#446]
Our current implementation of infinite scroll has problems, see #445 - and is also very slow. 

For comparison, try out the scroll perf on https://blog.algolia.com - it's like an absolute rocket. 

It turns out Algolia load JSON, whereas we instead make full page requests, parse the body, and then insert it into the existing page.

It would be really, really cool if Casper could behave the same way as Algolia's implementation.
(I haven't looked at it that closely, but I assume it's just using [Jetpack's infinite scroll](https://github.com/Automattic/jetpack/tree/master/modules/infinite-scroll) - for reference)

Changing to use Ghost API rather than full page request would require that the public API is enabled (so, we should probably detect that, and have a super simple fallback?) 

It would be great not to have to duplicate all of https://github.com/TryGhost/Casper/blob/master/partials/post-card.hbs when parsing the response, but I'm not sure how else to do it

**Comment by kevinansfield** [comment]
Closed via https://github.com/TryGhost/Casper/commit/41bcbb71570db0f829a2f0f1b5549f380d38d36a

Poor perf performance for our scroll was mostly down to parsing HTML into _jQuery_ DOM objects and unnecessary fade animations, using HTML rather than JSON should be marginally faster because we don't need to use templates to build DOM on the fly and the HTML pages are more likely to be cached and gzipped than API responses.
