### ISSUE TITLE
Tables with lots of content don't  do any word-breaking...

### ISSUE THREAD

**Issue by jessehouwing** [TryGhost/Casper#469]
Do you need help or have a question? Please come chat in our forum: https://forum.ghost.org 👫.

If you're filing a bug 🐛, please include the following information:

### Screenshot

![image](https://user-images.githubusercontent.com/4173387/43976820-45da8938-9ce2-11e8-8c36-89dccc986d4f.png)

https://jessehouwing.net/scaling-scrum-professionally-using-nexus-vsts/

### Steps to Reproduce
 
Put a very wide table in a markdown card:

```

| Scrum                                    | Nexus                                    |
|------------------------------------------|------------------------------------------|
| Scrum is a Framework, and it can encompass many good agile practices. Practices that work for one product and one organization may work differently for other products and organizations. | Nexus is a Framework, and to make it work, it needs to be extended with good agile practices. Practices that work for your product and organization may be different than those of another organization. Due to the added complexity of working with multiple teams, these practices are even more important. |
```

### Technical details

* Casper Version: 2.4.2
* Ghost Version: Ghost Pro
* Browser Version: Chrome 68
* OS Version: Windows 10 April 2018 edition

I'd expect the two halves of the table to be similar in size and for the table to fit the page width preferably.

I like that I can make the table scroll, but often this is undesired.

**Comment by TonnyORG** [comment]
@jessehouwing I bet this is not a bug, is actually a feature to support responsive tables. However, here is the fix: https://github.com/TryGhost/Casper/pull/482

**Comment by JohnONolan** [comment]
Table overflow is a deliberate design choice of casper and are intended to contain shortform content rather than longform content - so this break is expected.

Currently there's no way to easily support both along and short form content automatically, so we just went with the most common use-case.

In future, hopefully a wider range of Cards in the new koenig editor will allow us to more easily support various usecases. In the mean time, you can always modify your own copy of Casper (either directly, over via code injection overrides) to suit your specific needs
