### ISSUE TITLE
More social icons

### ISSUE THREAD

**Issue by MrAnnix** [TryGhost/Casper#490]
Would be awesome to have more social icons in the site-nav

**Comment by kevinansfield** [comment]
@MrAnnix you're free to add/change social icons to match the specific needs of your site. Casper is designed as a clean starting point to build from rather than being everything for everyone box which would end up being overly messy and poor out-of-the-box solution for the majority of sites.

If you need help modifying Casper to your needs please reach out on [our forum](https://forum.ghost.org), the community there is always very helpful 😄
