### ISSUE TITLE
Unsplash images: All `srcset` assets use the full-resolution image

### ISSUE THREAD

**Issue by spaceninja** [TryGhost/Casper#644]
If you set an Unsplash feature image, you'll see a proper set of responsive image code, with multiple assets specified in a `srcset` attribute. However, each image's assets actually use the same URL, for the full-sized Unsplash asset, meaning all mobile users are downloading the high-res desktop assets.

I looked at the code in the theme, and the HTML is correct. I'm guessing there's some sort of bug in the `img_url` helper, where it's not properly returning the specified `size` asset.

### Screenshot

![Screen Shot 2019-10-30 at 11 03 07 AM](https://user-images.githubusercontent.com/257309/67885461-e449e600-fb04-11e9-9461-c460f4b774de.png)

### Steps to Reproduce
 
 1. Set an Unsplash image as the featured image on a post
 2. View source of either the card view or the post page. See a `srcset` array where every image links to the full-size asset from Unsplash.

### Technical details

* Casper Version: 3.0.2
* Ghost Version: 3.0.2
* Browser Version: Chrome 78.0.3904.70
* OS Version: Mac OS 10.15

**Comment by kevinansfield** [comment]
Hey @spaceninja 👋 This is currently the expected behaviour - image resizing only works for uploaded images, not externally hosted images.

There is a feature request here for adding specific Unsplash support to the `{{img_url}}` helper which you could add your vote to 🙂 https://forum.ghost.org/t/unsplash-support-for-img-url-size/7081.

Closing this as it's a feature request rather than a bug. All feature requests are tracked on the forum at https://forum.ghost.org/c/Ideas
