### ISSUE TITLE
Social icons with 5.4.0

### ISSUE THREAD

**Issue by viriatusX** [TryGhost/Casper#907]
Hi,
with the latest Casper v.5.4.0 the option to add social icons to header has dissapeared?
It's very useful....
Can it be implemented again or explain how to recover this function please?
Thanks!

**Comment by minimaluminium** [comment]
Hey @viriatusX, the removal of social icons in `v5.4.0` was intentional which is a part of standardizing headers across all our official themes. Our current Facebook and Twitter links are structured data for SEO purposes, and won't be used on our themes anymore.

If anyone wants to bring back the links to their websites, the code can be taken from `v5.3.2` [here](https://github.com/TryGhost/Casper/blob/c7713df88f11bc2ff612457dfb51d6e1909a40e4/default.hbs#L49-L55).

**Comment by minimaluminium** [comment]
Just FYI, we now have a dedicated tutorial for adding social icons to the official themes with code injection method. https://ghost.org/tutorials/add-social-media-icons/#code-generator

**Comment by viriatusX** [comment]
> Just FYI, we now have a dedicated tutorial for adding social icons to the official themes with code injection method. https://ghost.org/tutorials/add-social-media-icons/

Thanks @minimaluminium! but it doesn't work with Casper 5.4.0. I just tried it now...
