### ISSUE TITLE
Account button no longer has rounded, white background

### ISSUE THREAD

**Issue by ryansechrest** [TryGhost/Casper#911]
Since the update, the account button no longer has a rounded, white background, making it difficult to read on darker publication backgrounds.

Looking at the source, it still seems to have a button class, but it's simply not rendering. The subscribe button is unchanged; it's only the account button after logging in.

On a separate note, and I can open a new issue if needed, under Settings > Design > Site-wide > Navigation layout, when choosing "Logo on cover," I don't see a logo appearing on the cover. "Logo in the middle" and "Stacked" show the logo perfectly fine.

**Comment by minimaluminium** [comment]
Hey @ryansechrest,

The account button background color is now fixed in [5.4.3](https://github.com/TryGhost/Casper/releases/tag/v5.4.3).

Re: Logo on cover mode, I've just tested this and it works as expected. The site title or logo should be centered with the site description in the cover section of the homepage when this navigation layout is selected. Is this working differently on your end?

**Comment by ryansechrest** [comment]
Hi @minimaluminium 

Attached is what I'm seeing. Before the update, I did toggle through these options and was seeing what you described.

https://user-images.githubusercontent.com/877536/207759511-99583f61-35d1-487e-878c-009c55d80280.mp4

**Comment by ryansechrest** [comment]
I know what's going on. It's because my header style (Center aligned, Left aligned, Hidden) is set to Hidden, because I didn't want the text to show, and because the other navigation layouts showed a logo, I had assumed it would show a logo, too, just not the header text.

**Comment by minimaluminium** [comment]
@ryansechrest Ohh, you're totally right! When the header style is hidden, the logo should be visible on the navbar. This is now fixed in 5.4.4 :)
